---
- name: Install freq
  git:
    repo: 'https://github.com/markbaggett/freq'
    dest: '/usr/local/share/freq'
    refspec: master
    update: yes
  tags: sof-elk_freq

- name: Create location for freq table storage
  file:
    dest: '/usr/local/lib/sof-elk'
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: sof-elk_freq

- name: Copy freq table to operational location
  copy:
    remote_src: yes
    src: /usr/local/share/freq/freqtable2018.freq
    dest: /usr/local/lib/sof-elk/freqtable2018.freq
  tags: sof-elk_freq

- name: Enable freq service
  systemd:
    name: /usr/local/sof-elk/lib/systemd/freq.service
    enabled: yes
  tags: sof-elk_freq

- name: Start freq service
  systemd:
    name: freq
    state: started
  tags: sof-elk_freq
