---
- name: Load all dashboards
  command: '/usr/local/sbin/load_all_dashboards.sh'
  tags: sof-elk_finalize

- name: Run the post-merge script
  command: '/usr/local/sof-elk/supporting-scripts/post_merge.sh'
  tags: sof-elk_finalize

- name: Restart Kibana
  systemd:
    name: kibana
    state: restarted
  tags: sof-elk_finalize
