---
# This playbook configures a single-instance SOF-ELK(R) system

- name: Run all preload steps required for a SOF-ELK system
  hosts: all
  become_method: sudo
  become_user: root

  roles:
    - sof-elk_base
    - elasticsearch
    - cerebro
    - logstash
    - filebeat
    - kibana
    - elastalert
    - domain_stats
    - freq

    - sof-elk_finalize
